### ISSUE TITLE
Error in /stores

### ISSUE THREAD

**Issue by bmkrocks1** [pjanusc85/store-finder-service#1]
{  
   "timestamp":1499438334320,
   "status":500,
   "error":"Internal Server Error",
   "exception":"feign.FeignException",
   "message":"status 403 reading GoogleSheetApi#get(String,Map); content:\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Requests from IP address 50.19.166.99 are blocked.\",\n    \"status\": \"PERMISSION_DENIED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.Help\",\n        \"links\": [\n          {\n            \"description\": \"Google developer console API key\",\n            \"url\": \"https://console.developers.google.com/project/780808657967/apiui/credential\"\n          }\n        ]\n      }\n    ]\n  }\n}\n",
   "path":"/stores"
}

**Comment by pjanusc85** [comment]
IP whitelisted
